name: Testes de unidade com pytest

on:
  push:
    branches: [ master ]  # ou main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com pytest e gerar relatório de cobertura
        run: |
          pytest --cov=app --cov-report=html --cov-report=term

      - name: Publicar relatório de cobertura no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./htmlcov
