name: Testes de unidade com pytest

on:
  push:
    branches: [ master ]  # ou 'main', conforme seu repositório

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python 3.11
        uses: actions/setup-python@v4
        with:
          # Versão do Python fixada em 3.11
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com pytest
        run: |
          pytest -v