name: Testes e Deploy Coverage

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com pytest e gerar relatório coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest --cov=app --cov-report=html

      - name: Listar htmlcov para debug
        run: ls -la htmlcov

      - name: Fazer upload do relatório coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Download do relatório coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: ./htmlcov

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./htmlcov
          publish_branch: gh-pages
          clean: true

