name: Testes de unidade com pytest

on:
  push:
    branches: [ master ]  # ou 'main', conforme seu repositório

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.10, 3.11]  # NÃO usar 3.1

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com pytest
        run: |
          pytest -v
