name: Testes e Deploy Coverage

on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes e gerar relatório de coverage
        run: |
          pytest --cov=./ --cov-report=html

      - name: Fazer upload do relatório de coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov

  deploy:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Download do relatório de coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: htmlcov

      - name: Publicar relatório no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./htmlcov
          clean: true
