name: Testes de unidade com pytest

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version:  [3.10, 3.11]

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com pytest
        run: |
          pytest
